---
- name: Get hostname and OS info
  hosts: all
  gather_facts: no

  tasks:
    - name: Print the hostname
      debug:
        msg: "The hostname is {{ ansible_hostname }}"

    - name: Print the operating system
      debug:
        msg: "The operating system is {{ ansible_facts['os_family'] }}"

    - name: Print the OS version
      debug:
        msg: "The OS version is {{ ansible_facts['distribution_version'] }}"
