---
- name: Upgrade all packages
  hosts: all
  become: yes

  tasks:
    - name: Update package cache and upgrade all packages (Debian/Ubuntu)
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_facts['os_family'] == "Debian"

    - name: Upgrade all packages (RedHat/CentOS/AlmaLinux/Rocky)
      yum:
        name: "*"
        state: latest
      when: ansible_facts['os_family'] == "RedHat"
